name: Update WorkFlow
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update WorkFlow
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN}}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ secrets.repoOrigin}}/contents/.github/workflows" | \
          jq -r '.[] | select(.type=="file") | .download_url' | while read url; do
              curl -H "Authorization: token ${{ secrets.TOKEN}}" -L $url -O
          done
